[tool.poetry]
name = "dogconfig"
description = "Django Digital Object Gate project configuration"
authors = [
    "Michal Gawor <m.j.gawor@uu.nl>"
]
include = [
    { path = "./templates", format = ["wheel"]}
]
packages = [
    { include = "dogproject"},
]

