name: Digital Object Gate Django webservices CI Workflow
on: [push]
defaults:
    run:
        shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOGLIB_VERSION = 1.0.0-rc4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - run: python -V 

      - name: Install DOGlib
        run: |
          git clone --depth 1 --branch 1.0.0-rc4 https://github.com/clarin-eric/DOGlib.git
          pip install ./DOGlib -r ./DOGlib/requirements.txt      
      - name: Install DOG applications
        run: |
          pip install ./dog_apps -r requirements.txt
      - name: Run Django server
        run: |
          python dog_config/manage.py runserver
      - name: Save OpenAPI schema
        run: |
          curl https://localhost:8000/openapi > openapi.json
          cat openapi.json

