name: Digital Object Gate Django webservices CI Workflow
on: [push]
defaults:
    run:
        shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOGLIB_VERSION: "1.0.2"
      PYCURL_SSL_LIBRARY: openssl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.7"
      
      - name: Update package manager
        run: |
          sudo apt-get update 
          pip install wheel

      - name: Install DOGlib
        run: |
          sudo apt-get install libxml2-dev libxslt-dev libssl-dev libcurl4-openssl-dev
          git clone --depth 1 --branch ${{ env.DOGLIB_VERSION }} https://github.com/clarin-eric/DOGlib.git
          pip install ./DOGlib -r ./DOGlib/requirements.txt
      - name: Install DOG applications
        run: |
          pip install django-cors-headers
          pip install djangorestframework
          pip install django-rest-swagger
          pip install django-debug-toolbar
          pip install drf-yasg
          pip install ./dogapi
          pip install ./dogui
          pip install ./dogconfig
      - name: Test app
        env:
          EUROPEANA_WSKEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./runtests.py
          screen -m -d python ./dogconfig/manage.py runserver 127.0.0.1:8000 --settings ./dogconfig/dogproject/settings.py
          sleep 10
          [ $(curl -LI 127.0.0.1:8000/swagger.json -o /dev/null -w '%{http_code}\n' -s) == 200 ] && echo "Local host accessible"  
