name: Digital Object Gate Django webservices CI Workflow
on: [push]
defaults:
    run:
        shell: bash
        working-directory: client
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - run: | 
          pip --help | cat

      - name: Install DOGlib
        run: pip install -e git://github.com/clarin-eric/DOGlib.git@1.0.0-rc4#egg=doglib
      - name: Install DOG applications
        run: |
          pip install ./dog_apps
      - name: Run Django server
        run: |
          python dog_config/manage.py runserver
      - name: Save OpenAPI schema
        run: |
          curl https://localhost:8000/openapi > openapi.json
          cat openapi.json

