name: Digital Object Gate Django webservices CI Workflow
on: [push]
defaults:
    run:
        shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOGLIB_VERSION: "1.0.1"
      PYCURL_SSL_LIBRARY: openssl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"
      
      - run: |
          sudo apt-get update 
          pip install wheel

      - name: Install DOGlib
        run: |
          sudo apt-get install libxml2-dev libxslt-dev libssl-dev libcurl4-openssl-dev
          git clone --depth 1 --branch ${{ env.DOGLIB_VERSION }} https://github.com/clarin-eric/DOGlib.git
          pip install ./DOGlib -r ./DOGlib/requirements.txt      
      - name: Install DOG applications
        run: |
          pip install djangorestframework
          pip install ./dog-api
      - name: Run Django server and try to access swagger page
        run: |
          screen -m -d python dog-config/manage.py runserver 127.0.0.1:8000
          sleep 10
          curl -f -L 127.0.0.1:8000/swagger.json
