name: Digital Object Gate Django webservices CI Workflow
on: [push]
defaults:
    run:
        shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOGLIB_VERSION: 1.0.0-rc6
      PYCURL_SSL_LIBRARY: openssl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - run: python -V 

      - name: Install DOGlib
        run: |
          sudo apt-get install libxml2-dev libxslt-dev libssl-dev libcurl4-openssl-dev
          git clone --depth 1 --branch ${{ env.DOGLIB_VERSION }} https://github.com/clarin-eric/DOGlib.git
          pip install ./DOGlib -r ./DOGlib/requirements.txt      
      - name: Install DOG applications
        run: |
          pip install djangorestframework
          pip install pyyml
          pip install uritemplate
          pip install ./dog_apps
      - name: Run Django server and dump OpenAPI schems
        run: |
          screen -m -d python dog_config/manage.py runserver 127.0.0.1:8000
          sleep 10
          curl -L 127.0.0.1:8000/openapi > openapi.json
          cat openapi.json
      - name: Push generated schemas
        run: |
          git config --global user.name "DOG-github-actions[bot]"
          git config --global user.email "DigitalObjectGate[bot]@users"
          git add openapi.json
          git commit -m "CI push OpenAPI schemas"
          git push
          

